services:
  app:
    build: .
    ports:
      - "${PORT:-3333}:3333"
    environment:
      - NODE_DB_CONNECTION=postgres://user:password@db:5432/receitas_db
      - PORT=3333
      - NODE_ENV=production
      - LOG_LEVEL=info
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=receitas_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d receitas_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
